Homework media queries
przemekjuzwiszin/homepage-2-pd pull request #35
Opened 2020-12-18 16:19 UTC by przemekjuzwiszin

Hey guys and ladies:) I fink that code is good. I now is Christmas time but please check this little work that I made. And enjoy:) Keep doing the good job and thanks for spending your time to check on my code:) Regards to team Frontend Company.

2020-12-19 20:36 UTC, karbowskam commented on index.html
>            <li class="navigation__item">
Hm, where is </li>? :) I can't see closing tag

2020-12-19 20:37 UTC, karbowskam commented on index.html
>            <li class="navigation__item">
I mean where is "</li>" :)?

2020-12-19 20:39 UTC, karbowskam commented on index.html
>            <li class="navigation__item">
I cant write down this closing tag, it change my word to white space. I can't see "/li"

2020-12-19 21:44 UTC, robson60000 requested changes

2020-12-19 21:44 UTC, robson60000 commented on .vscode/settings.json
> +{
You should add entire .vscode folder to gitignore.
This is VSCode configuration directory and it should not be in the repo

2020-12-19 21:44 UTC, robson60000 commented on index.html
>            <li class="navigation__item">
Do you mean `<li>` from the 18th line?
It is in 20th line. Use this button to expand the code.
![image](https://user-images.githubusercontent.com/70059619/102700151-460a6980-424b-11eb-858a-08a4fdf67f7b.png)
For pasting the code use this button:
![image](https://user-images.githubusercontent.com/70059619/102700183-81a53380-424b-11eb-8681-b34b4086df71.png)

2020-12-28 12:01 UTC, przemekjuzwiszin commented
Hi:) please check this ignore file. Is it o.k now? Do I need to correct something?

2020-12-29 05:09 UTC, robson60000 approved these changes

2021-01-01 15:35 UTC, merged